name       : perl-extutils-xspp
version    : 0.18
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SM/SMUELLER/ExtUtils-XSpp-0.18.tar.gz : 9176ad646729e3bd27cf7abf114bedd3424bff1ba61185cfc7d54f3a9223a8ff
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : ExtUtils::XSpp - XS for C++
description: |
    ExtUtils::XSpp - XS for C++
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
